### ISSUE TITLE
Color Pointer Truncated in Image Viewer

### ISSUE THREAD

**Issue by Curran919** [DaltonLens/DaltonLens#4]
The color pointer when using the 'highlight similar' images filter clips to remain within the parent window. So when grabbing a small area, you never see the color pointer.

**Comment by nburrus** [comment]
I've reworked the UI to include the color pointer in the controls window now. This avoids that problem and simplifies the viewer a bit. Also it's now possible to activate the global color pointer (Ctrl + Alt + Win + Space) if the viewer is already active, so we can inspect the values of the applied filters. If you don't select a new region and exit with q or escape then the existing viewer will stay there.

Let's see if we like this better, it's easy to re-enable the "follow mouse" overlay when the window is large enough, but I thought I'd keep it simple and avoid a conditional UI.
